apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base
images:
  - name: beomsun22/testsvc
    newName: beomsun22/testsvc
    newTag: c66a3691f290b1f69e85501bc42d7765ac72d82e
