apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base
images:
  - name: testsvc
    newName: testsvc
    newTag: beomsun22/testsvc:5da053b7d3d70369599f1a2f1b86399488372306
