# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  push:
   paths-ignore:
    - ".github/workflows/**"
    - "kustomize/**"
env:
  tag: ${{ github.sha }}
  dockerimage_name: ${{ secrets.DOCKER_USERNAME }}/testsvc:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest  
    defaults:
      run:
       working-directory: ./src/testservicev1
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: bulid
      run: ./gradlew build -x test
    - name: check bulid
      run: ls ./build/libs
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
    - name: docker build & push
      run: |
         docker build -t ${{ env.dockerimage_name }} .   
         docker push ${{ env.dockerimage_name }}
    - name: view manifast
      run: cat ./kustomize/overlays/testservice/dev/kustomization.yaml
    - name: change yaml for k8s
      run: |
            cat <<EOF> ./kustomize/overlays/testservice/dev/kustomization.yaml 
            apiVersion: kustomize.config.k8s.io/v1beta1
            kind: Kustomization
            resources:
            - ../../../base
            images:
              - name: ${{ secrets.DOCKER_USERNAME }}/testsvc
                newName: ${{ secrets.DOCKER_USERNAME }}/testsvc
                newTag: ${{ env.tag }}
            EOF
    - name: after change        
      run: cat kustomization.yaml
    - name: Commit report
      run: |
          git config --global user.name 'beomsun66'
          git config --global user.email 'beomsun66@google.com'
          git commit -am "relese/${{ env.tag }}"
          git push
